name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta una vez al día

  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Generar Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=green&color_dots=#ccffcc,#99ff99,#66ff66,#33cc33,#009900

      - name: Subir archivos generados
        uses: actions/upload-artifact@v4
        with:
          name: github-snake
          path: dist/github-snake.svg

      - name: Subir imagen al repositorio
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull origin main
          git add dist/github-snake.svg
          git commit -m "Updated snake animation"
          git push origin main
